name: Send shanbay today new words to telegram

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"
  push:
    branches:
      - master
    paths:
      - shanbay.js
env:
  TZ: Asia/Shanghai

jobs:
  sender:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FedericoCarboni/setup-ffmpeg@v1-beta
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run Script
        run: |
          node shanbay.js ${{ secrets.TELE_TOKEN }} ${{ secrets.TELE_CHAT_ID }} "${{ secrets.SHANBAY_COOKIE }}"
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "MP3_NEW/1.mp3, MP3_REVIEW/1.mp3"
      - name: use ffmpeg combine and send
        id: setup-ffmpeg
        run: | 
          ffmpeg -y -f concat -safe 0 -i <(find "$(pwd)"/MP3_NEW -iname "*.mp3" -printf "file "%p"\n" | sort) -c copy "$(pwd)"/$(date +"%m%d")_new_words.mp3
          ffmpeg -y -f concat -safe 0 -i <(find "$(pwd)"/MP3_REVIEW -iname "*.mp3" -printf "file "%p"\n" | sort) -c copy "$(pwd)"/$(date +"%m%d")_review_words.mp3
          curl -v -F "chat_id=${{ secrets.TELE_CHAT_ID }}" -F document=@$(date +"%m%d")_new_words.mp3 https://api.telegram.org/bot${{ secrets.TELE_TOKEN }}/sendDocument
          curl -v -F "chat_id=${{ secrets.TELE_CHAT_ID }}" -F document=@$(date +"%m%d")_review_words.mp3 https://api.telegram.org/bot${{ secrets.TELE_TOKEN }}/sendDocument
        if: steps.check_files.outputs.files_exists == 'true'
